# Generated by Django 3.1.4 on 2020-12-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(default='MUMBAI', max_length=64)),
                ('district', models.CharField(default='GREATER BOMBAY', max_length=64)),
                ('state', models.CharField(default='MAHARASHTRA', max_length=64)),
            ],
        ),
    ]
